In [3]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.23.5'

In [6]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a.nbytes

80

In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [17]:
z = np.arange(9)
z
z.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


In [21]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
z = np.random.random((3,3,3))
z

array([[[0.73263832, 0.51478507, 0.83471374],
        [0.71837336, 0.73540372, 0.19569398],
        [0.25824904, 0.80580162, 0.93821704]],

       [[0.82338898, 0.46402158, 0.89320648],
        [0.01999907, 0.04885467, 0.85392208],
        [0.11654672, 0.24880481, 0.28122618]],

       [[0.45173948, 0.49466339, 0.54847698],
        [0.85301865, 0.88995469, 0.93534205],
        [0.03175221, 0.2392544 , 0.20201097]]])

In [31]:
z = np.random.random((10,10))
z.min()
z.max()

0.9951486829030395

In [34]:
output = np.ones((3,3))
print(output)
output[1,1] = 0
output

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [36]:
 Z= np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)

In [5]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [7]:
filt = ((df['animal'] == 'cat') & (df['age']<3))
df.loc[filt]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [8]:
animal_grp = df.groupby(['animal'])
animal_grp

In [9]:
animal_grp.get_group('cat')

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
h    cat  NaN       1      yes

In [11]:
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

In [12]:
animal_grp['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64